const EventTypes = {

    PROCESS_CREATED: "PROCESS_CREATED",
    PROCESS_TERMINATED: "PROCESS_TERMINATED",

    NETWORK_CONNECTION: "NETWORK_CONNECTION",

    FILE_CREATED: "FILE_CREATED",
    FILE_MODIFIED: "FILE_MODIFIED",
    FILE_DELETED: "FILE_DELETED",

    REGISTRY_CHANGED: "REGISTRY_CHANGED",

    EVENTLOG_CREATED: "EVENTLOG_CREATED",

    ALERT_CREATED: "ALERT_CREATED"

};

module.exports = EventTypes;