const DEFAULT_ROLES = [
  {
    id: 'role-super-admin',
    name: 'SUPER_ADMIN',
    description: 'Full system and platform access across all features and administration.',
    permissions: JSON.stringify(['*']),
  },
  {
    id: 'role-platform-admin',
    name: 'PLATFORM_ADMIN',
    description: 'Administrative management of users, courses, simulations, and analytics.',
    permissions: JSON.stringify([
      'users:*',
      'courses:*',
      'simulations:*',
      'certifications:*',
      'analytics:*',
      'audit:*',
    ]),
  },
  {
    id: 'role-user-admin',
    name: 'USER_ADMIN',
    description: 'Manage users, access permissions, and account roles.',
    permissions: JSON.stringify(['users:*']),
  },
  {
    id: 'role-course-admin',
    name: 'COURSE_ADMIN',
    description: 'Manage course catalog, modules, lessons, and quizzes.',
    permissions: JSON.stringify(['courses:*']),
  },
  {
    id: 'role-simulation-admin',
    name: 'SIMULATION_ADMIN',
    description: 'Manage social engineering simulations and lab scenarios.',
    permissions: JSON.stringify(['simulations:*']),
  },
  {
    id: 'role-certification-admin',
    name: 'CERTIFICATION_ADMIN',
    description: 'Issue, verify, and revoke security credentials.',
    permissions: JSON.stringify(['certifications:*']),
  },
  {
    id: 'role-flotbot-sec-admin',
    name: 'FLOTBOT_SECURITY_ADMIN',
    description: 'Full FlotBot endpoint security administration, IOC management, and threat rules.',
    permissions: JSON.stringify([
      'flotbot:*',
      'security:*',
      'rules:*',
      'iocs:*',
      'audit:*',
    ]),
  },
  {
    id: 'role-security-analyst',
    name: 'SECURITY_ANALYST',
    description: 'Monitor threat alerts, review user security behaviour, and inspect IOCs.',
    permissions: JSON.stringify([
      'flotbot:read',
      'flotbot:ack',
      'flotbot:inspect',
      'security:read',
      'analytics:security',
    ]),
  },
  {
    id: 'role-analyst',
    name: 'ANALYST',
    description: 'Access aggregated educational and security analytics.',
    permissions: JSON.stringify(['analytics:*', 'reports:*']),
  },
  {
    id: 'role-student',
    name: 'STUDENT',
    description: 'Standard student learner account for courses, simulations, and certifications.',
    permissions: JSON.stringify([
      'courses:read',
      'courses:enroll',
      'courses:progress',
      'simulations:play',
      'certifications:read',
      'profile:manage',
    ]),
  },
];

const DEFAULT_THREAT_RULES = [
  {
    rule_id: 'RULE-SYS-001',
    name: 'Encoded PowerShell Execution',
    category: 'System',
    severity: 'HIGH',
    description: 'Detects base64-encoded or hidden PowerShell process executions commonly used in dropper payloads.',
    enabled: 1,
    config_json: JSON.stringify({ pattern: 'powershell.*-enc|-encodedcommand|-w hidden', mitre: ['T1059.001'] }),
  },
  {
    rule_id: 'RULE-SYS-002',
    name: 'Suspicious CMD Spawn from Office',
    category: 'System',
    severity: 'CRITICAL',
    description: 'Detects Word/Excel spawning command interpreter shells.',
    enabled: 1,
    config_json: JSON.stringify({ parent: ['winword.exe', 'excel.exe'], child: ['cmd.exe', 'powershell.exe'], mitre: ['T1059.003'] }),
  },
  {
    rule_id: 'RULE-NET-001',
    name: 'Reverse Shell Outbound Connection',
    category: 'Network',
    severity: 'CRITICAL',
    description: 'Detects shell processes with outbound interactive socket connections to remote IPs.',
    enabled: 1,
    config_json: JSON.stringify({ ports: [4444, 1337, 8080, 9001], mitre: ['T1059', 'T1071'] }),
  },
  {
    rule_id: 'RULE-NET-002',
    name: 'C2 Periodic Beaconing',
    category: 'Network',
    severity: 'HIGH',
    description: 'Detects regular heartbeat network connections to suspicious remote endpoints.',
    enabled: 1,
    config_json: JSON.stringify({ intervalMs: 5000, varianceThreshold: 0.15, mitre: ['T1071.001'] }),
  },
  {
    rule_id: 'RULE-REG-001',
    name: 'Run Key Persistence Injection',
    category: 'Registry',
    severity: 'HIGH',
    description: 'Detects unauthorized modifications to Windows Run / RunOnce startup keys.',
    enabled: 1,
    config_json: JSON.stringify({ keys: ['HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run'], mitre: ['T1547.001'] }),
  },
  {
    rule_id: 'RULE-FILE-001',
    name: 'Suspicious Executable Drop in Temp',
    category: 'File',
    severity: 'HIGH',
    description: 'Detects binaries dropped into Temp or AppData directories.',
    enabled: 1,
    config_json: JSON.stringify({ paths: ['%TEMP%', '%APPDATA%'], extensions: ['.exe', '.dll', '.scr'], mitre: ['T1105'] }),
  },
  {
    rule_id: 'RULE-FILE-002',
    name: 'Mass File Extension Modification (Ransomware)',
    category: 'File',
    severity: 'CRITICAL',
    description: 'Detects rapid mass renaming or encryption of files across user folders.',
    enabled: 1,
    config_json: JSON.stringify({ threshold: 25, windowSeconds: 5, mitre: ['T1486'] }),
  },
];

const DEFAULT_IOCS = [
  {
    id: 'ioc-1',
    type: 'ip',
    value: '185.220.101.5',
    threat_name: 'Phishing Campaign C2 Host',
    severity: 'HIGH',
    status: 'active',
    added_by: 'FlotBot Rule Engine',
    note: 'Observed during credential harvesting domain hosting',
  },
  {
    id: 'ioc-2',
    type: 'domain',
    value: 'auth-security-update-verify.com',
    threat_name: 'Lookalike OAuth Phishing Portal',
    severity: 'CRITICAL',
    status: 'active',
    added_by: 'Security Analyst',
    note: 'Impersonating Microsoft 365 identity verification',
  },
  {
    id: 'ioc-3',
    type: 'hash',
    value: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    threat_name: 'Emotet Dropper Payload SHA-256',
    severity: 'CRITICAL',
    status: 'active',
    added_by: 'Threat Intel Engine',
    note: 'Known malware dropper hash',
  },
  {
    id: 'ioc-4',
    type: 'process_name',
    value: 'mimikatz.exe',
    threat_name: 'Credential Dumping Tool',
    severity: 'CRITICAL',
    status: 'active',
    added_by: 'FlotBot Security Admin',
    note: 'LSASS memory dumping utility',
  },
];

const DEFAULT_SETTINGS = [
  { key: 'scanInterval', value: '5000' },
  { key: 'aiProvider', value: 'gemini' },
  { key: 'aiMode', value: 'auto' },
  { key: 'aiPrivacyMode', value: 'false' },
  { key: 'notificationsEnabled', value: 'true' },
  { key: 'soundEnabled', value: 'true' },
  { key: 'retentionDays', value: '30' },
  { key: 'networkIsolated', value: 'false' },
  { key: 'screenSecurityMode', value: 'MANUAL' },
];

module.exports = {
  DEFAULT_ROLES,
  DEFAULT_THREAT_RULES,
  DEFAULT_IOCS,
  DEFAULT_SETTINGS,
};
